# Generated by Django 3.1.5 on 2022-09-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bazar',
            name='descricao',
        ),
        migrations.AddField(
            model_name='bazar',
            name='total_participantes',
            field=models.IntegerField(null=True),
        ),
    ]
