# Generated by Django 3.1.5 on 2022-09-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_auto_20220914_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bazar',
            name='total_participantes',
            field=models.DecimalField(decimal_places=0, default=50, max_digits=2),
        ),
    ]
