# Generated by Django 3.1.5 on 2022-09-13 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='organizador',
            name='senha',
        ),
    ]
